<?php

		$charset_collate = $wpdb->get_charset_collate();

		$table_name = $wpdb->prefix . str_replace( ' ', '_', str_replace( 'wp ', '', strtolower( WS_RESCUE_ROVER_PRO_NAME . '_foster_apps' ) ) );

		$sql = "CREATE TABLE IF NOT EXISTS `{$table_name}` (
    id INT(10) NOT NULL AUTO_INCREMENT,
    unique_ID INT(5) NOT NULL,
    date_created DATETIME NULL,
    date_last_updated TIMESTAMP NULL,
    archived CHAR(1) NULL,
    initial_review_status VARCHAR(12) NULL,
    initial_review_notes TEXT NULL,
    counselor VARCHAR(10) NULL,
    dog_suggestions TEXT NULL,
    dog_requirements VARCHAR(12) NULL,
    phone_interview_status TEXT NULL,
    phone_interview_notes VARCHAR(12) NULL,
    home_check_status TEXT NULL,
    home_check_notes TEXT NULL,
    meeting_notes VARCHAR(20) NULL,
    first_name VARCHAR(20) NULL,
    last_name VARCHAR(30) NULL,
    street VARCHAR(20) NULL,
    city VARCHAR(30) NULL,
    state VARCHAR(5) NULL,
    zipcode VARCHAR(50) NULL,
    email VARCHAR(12) NULL,
    home_phone VARCHAR(12) NULL,
    work_cell_phone VARCHAR(12) NULL,
    overall_status TEXT NULL,
    remaining_answers VARCHAR(30) NULL,
    dog_interested_in VARCHAR(30) NULL,
    heard_from VARCHAR(50) NULL,
    How_long_at_this_address VARCHAR(10) NULL,
    Best_Number_Call VARCHAR(30) NULL,
    Best_Time_Call VARCHAR(3) NULL,
    My_Age VARCHAR(50) NULL,
    Employer VARCHAR(25) NULL,
    Work_Phone VARCHAR(4) NULL,
    Own_or_Rent VARCHAR(10) NULL,
    Type_of_home VARCHAR(3) NULL,
    Dogs_Allowed_in_complex VARCHAR(50) NULL,
    Landlord VARCHAR(3) NULL,
    Yard_fenced_in VARCHAR(30) NULL,
    How_tall_is_fence VARCHAR(3) NULL,
    Locks_on_all_gates VARCHAR(3) NULL,
    Do_you_have_a_pool VARCHAR(3) NULL,
    Pool_fenced_in VARCHAR(3) NULL,
    Do_you_have_children VARCHAR(15) NULL,
    gender_age_1 VARCHAR(35) NULL,
    allergies_1 VARCHAR(15) NULL,
    gender_age_2 VARCHAR(35) NULL,
    allergies_2 VARCHAR(15) NULL,
    gender_age_3 VARCHAR(35) NULL,
    allergies_3 VARCHAR(15) NULL,
    fostered_before VARCHAR(3) NULL,
    your_pets_get_along TEXT NULL,
    ineligible_traits TEXT NULL,
    type_comfortable_fostering VARCHAR(99) NULL,
    Where_will_the_dog_sleep TEXT NULL,
    Alone_during_the_day VARCHAR(99) NULL,
    How_much_time_outside VARCHAR(99) NULL,
    Exercise_Plan VARCHAR(3) NULL,
    Doggie_Door VARCHAR(99) NULL,
    Responsible_for_dog VARCHAR(3) NULL,
    Do_you_have_other_pets VARCHAR(99) NULL,
    Breed_Gender_Age_1 VARCHAR(99) NULL,
    Breed_Gender_Age_2 VARCHAR(99) NULL,
    Breed_Gender_Age_3 VARCHAR(99) NULL,
    Breed_Gender_Age_4 VARCHAR(99) NULL,
    Vets_name_and_phone TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY unique_ID (unique_ID)

) $charset_collate;";

	require_once ABSPATH . 'wp-admin/includes/upgrade.php';
			dbDelta( $sql );
			update_option( 'ws_rescure_rover_pro_database_version', WS_RESCUE_ROVER_PRO_VERSION );